import { IMAGES } from "@/contants/images";

export const workoutData = [
  {
    image: IMAGES.workout1,
    title: "Simple Home Workout",
    price: "$2.75",
    duration: "30 min/day",
    weeks: 3,
    isFree: true,
  },
  {
    image: IMAGES.workout2,
    title: "Weekly Workout Routine",
    price: "$5.60",
    duration: "30 min/day",
    weeks: 2,
    isFree: true,
  },
  {
    image: IMAGES.workout3,
    title: "Lower Body Workout",
    price: "$4.10",
    duration: "30 min/day",
    weeks: 1,
    isFree: false,
  },
  {
    image: IMAGES.workout2,
    title: "Weekly Workout Routine",
    price: "$5.60",
    duration: "30 min/day",
    weeks: 2,
    isFree: true,
  },
  {
    image: IMAGES.workout1,
    title: "Simple Home Workout",
    price: "$2.75",
    duration: "30 min/day",
    weeks: 3,
    isFree: true,
  },
  {
    image: IMAGES.workout2,
    title: "Weekly Workout Routine",
    price: "$5.60",
    duration: "30 min/day",
    weeks: 2,
    isFree: true,
  },
  {
    image: IMAGES.workout3,
    title: "Lower Body Workout",
    price: "$4.10",
    duration: "30 min/day",
    weeks: 1,
    isFree: false,
  },
  {
    image: IMAGES.workout2,
    title: "Weekly Workout Routine",
    price: "$5.60",
    duration: "30 min/day",
    weeks: 2,
    isFree: true,
  },
  {
    image: IMAGES.workout1,
    title: "Simple Home Workout",
    price: "$2.75",
    duration: "30 min/day",
    weeks: 3,
    isFree: true,
  },
  {
    image: IMAGES.workout2,
    title: "Weekly Workout Routine",
    price: "$5.60",
    duration: "30 min/day",
    weeks: 2,
    isFree: true,
  },
  {
    image: IMAGES.workout3,
    title: "Lower Body Workout",
    price: "$4.10",
    duration: "30 min/day",
    weeks: 1,
    isFree: false,
  },
  {
    image: IMAGES.workout2,
    title: "Weekly Workout Routine",
    price: "$5.60",
    duration: "30 min/day",
    weeks: 2,
    isFree: true,
  },
];
