const commentList = [
  {
    id: 1,
    name: "Chloe Decker",
    time: "2h",
    commentText: "Love the focus on controlled movement—so important!",
    userPic: "https://randomuser.me/api/portraits/women/10.jpg",
    replies: [
      {
        id: 101,
        name: "Lucifer Morningstar",
        time: "1h",
        commentText: "Agreed! Form is everything 💯",
        userPic: "https://randomuser.me/api/portraits/men/32.jpg",
      },
    ],
  },
  {
    id: 2,
    name: "Lucifer Morningstar",
    time: "4h",
    commentText: "Great combo of mobility + strength. Saving this.",
    userPic: "https://randomuser.me/api/portraits/men/32.jpg",
  },
  {
    id: 3,
    name: "Dan Espinoza",
    time: "7h",
    commentText:
      "Saved this workout—looks intense! Adding it to my next session ✅",
    userPic: "https://randomuser.me/api/portraits/men/55.jpg",
    replies: [
      {
        id: 102,
        name: "Jake Peralta",
        time: "3h",
        commentText: "Insane energy as always 🙌, Your progress is inspiring!",
        userPic: "https://randomuser.me/api/portraits/men/51.jpg",
      },
      {
        id: 103,
        name: "Amy Santiago",
        time: "2h",
        commentText: "Let’s try it this weekend!",
        userPic: "https://randomuser.me/api/portraits/women/41.jpg",
      },
    ],
  },
  {
    id: 4,
    name: "Lucy Marvick",
    time: "8h",
    commentText: "You make it look so easy! Gotta try this routine myself 💥",
    userPic: "https://randomuser.me/api/portraits/women/14.jpg",
  },
  {
    id: 5,
    name: "Suzane Mark",
    time: "1h",
    commentText: "Insane energy as always 🙌, Your progress is inspiring 👊",
    userPic: "https://randomuser.me/api/portraits/women/21.jpg",
  },
  {
    id: 6,
    name: "Robert Phelps",
    time: "2h",
    commentText: "This routine is next level. Subscribed 🔥",
    userPic: "https://randomuser.me/api/portraits/men/18.jpg",
    replies: [
      {
        id: 104,
        name: "Leo Mendes",
        time: "15m",
        commentText: "That was my favorite part too!",
        userPic: "https://randomuser.me/api/portraits/men/71.jpg",
      },
    ],
  },
  {
    id: 7,
    name: "Ella Watson",
    time: "30m",
    commentText: "Loved the warm-up section. Really helpful!",
    userPic: "https://randomuser.me/api/portraits/women/30.jpg",
  },
  {
    id: 8,
    name: "Mike Chandler",
    time: "5h",
    commentText: "How do you stay so consistent? Totally impressed!",
    userPic: "https://randomuser.me/api/portraits/men/40.jpg",
  },
  {
    id: 9,
    name: "Rachel Brooks",
    time: "12h",
    commentText: "These routines changed my mornings. Thank you!",
    userPic: "https://randomuser.me/api/portraits/women/37.jpg",
  },
  {
    id: 10,
    name: "Tom Harris",
    time: "6h",
    commentText: "Man, those squats hit different 🔥🔥",
    userPic: "https://randomuser.me/api/portraits/men/62.jpg",
  },
  {
    id: 11,
    name: "Olivia Kane",
    time: "10h",
    commentText: "Perfect for my HIIT days. Bookmarked!",
    userPic: "https://randomuser.me/api/portraits/women/45.jpg",
  },
  {
    id: 12,
    name: "Nate River",
    time: "9h",
    commentText: "The transitions are so clean! Respect 💯",
    userPic: "https://randomuser.me/api/portraits/men/12.jpg",
  },
  {
    id: 13,
    name: "Harper Glenn",
    time: "3h",
    commentText: "You're my fitness inspiration 🫶",
    userPic: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: 14,
    name: "Chris Vance",
    time: "2d",
    commentText: "Added to my Sunday grind 💪",
    userPic: "https://randomuser.me/api/portraits/men/28.jpg",
  },
  {
    id: 15,
    name: "Grace Miller",
    time: "5m",
    commentText: "Need more like this! Saved 💾",
    userPic: "https://randomuser.me/api/portraits/women/60.jpg",
  },
  {
    id: 16,
    name: "Leo Mendes",
    time: "11h",
    commentText: "So motivating! I’m fired up 🔥",
    userPic: "https://randomuser.me/api/portraits/men/71.jpg",
  },
  {
    id: 17,
    name: "Isla Reid",
    time: "20m",
    commentText: "Just finished this and I feel amazing!",
    userPic: "https://randomuser.me/api/portraits/women/66.jpg",
  },
  {
    id: 18,
    name: "Nathan Blake",
    time: "4d",
    commentText: "Every rep looks powerful. 🔁 Replay mode!",
    userPic: "https://randomuser.me/api/portraits/men/47.jpg",
  },
  {
    id: 19,
    name: "Amy Santiago",
    time: "1d",
    commentText: "Solid core section. Definitely doing this 💥",
    userPic: "https://randomuser.me/api/portraits/women/41.jpg",
  },
  {
    id: 20,
    name: "Jake Peralta",
    time: "14h",
    commentText: "Cool moves, cool vibe, cool person 😎",
    userPic: "https://randomuser.me/api/portraits/men/51.jpg",
  },
  {
    id: 21,
    name: "Maya Angel",
    time: "8m",
    commentText: "My legs are shaking and I love it 😂",
    userPic: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    id: 22,
    name: "James Heller",
    time: "3d",
    commentText: "Bro this is elite content",
    userPic: "https://randomuser.me/api/portraits/men/65.jpg",
  },
  {
    id: 23,
    name: "Sophia Bright",
    time: "22h",
    commentText: "Can’t believe how helpful this was 💯",
    userPic: "https://randomuser.me/api/portraits/women/24.jpg",
  },
  {
    id: 24,
    name: "Ethan Brooks",
    time: "1h",
    commentText: "You earned a new follower 💥",
    userPic: "https://randomuser.me/api/portraits/men/15.jpg",
  },
  {
    id: 25,
    name: "Zara Quinn",
    time: "17m",
    commentText: "The energy is unmatched ⚡️",
    userPic: "https://randomuser.me/api/portraits/women/27.jpg",
  },
  {
    id: 26,
    name: "Vincent Cross",
    time: "6d",
    commentText: "Tried this today. Brutal but worth it!",
    userPic: "https://randomuser.me/api/portraits/men/20.jpg",
  },
  {
    id: 27,
    name: "Lena Gray",
    time: "9m",
    commentText: "I showed this to my gym buddy and she’s obsessed 😍",
    userPic: "https://randomuser.me/api/portraits/women/16.jpg",
  },
  {
    id: 28,
    name: "Andre Wallace",
    time: "4h",
    commentText: "How are you not out of breath?! 😮‍💨",
    userPic: "https://randomuser.me/api/portraits/men/75.jpg",
  },
  {
    id: 29,
    name: "Naomi Chase",
    time: "13h",
    commentText: "Saving this forever. Legit awesome 🔒",
    userPic: "https://randomuser.me/api/portraits/women/18.jpg",
  },
  {
    id: 30,
    name: "Tony Blake",
    time: "2d",
    commentText: "Your content is pure fire. 🔥🔥🔥",
    userPic: "https://randomuser.me/api/portraits/men/33.jpg",
  },
];

export default commentList;
